# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1313950197);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1313950197);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1313950197);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1313950197);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 640000);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.startup.homepage_override.buildID", "20110419185614");
user_pref("browser.startup.homepage_override.mstone", "rv:2.0");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "globalmenu@ubuntu.com:1.0.2,ubufox@ubuntu.com:0.9,{972ce4c6-7e08-4474-a285-3208198ce6fd}:4.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1303772427000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1313203600000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1303772210000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1313203600000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/globalmenu@ubuntu.com\",\"mtime\":1303772211000}}}]");
user_pref("extensions.lastAppVersion", "4.0");
user_pref("extensions.pendingOperations", false);
user_pref("idle.lastDailyNotification", 1313953959);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1313953959);
user_pref("places.history.expiration.transient_current_max_pages", 20996);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1313953959);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1316542080);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
